// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhknjdqyvxorkrcvxyqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoa25qZHF5dnhvcmtyY3Z4eXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1ODYwODIsImV4cCI6MjA1MzE2MjA4Mn0.y_kCJpGCFwsq6W71n6psONkHYjSr97A50XyEW0mCeto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);